import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import ItemDetail from "../ItemDetail/ItemDetail";
import "./ItemDetailContainer.scss";

let productList = [
  {
    bundle: "spring",
    id: 101,
    product: "Papa",
    description: "remolacha",
    image: "src/resources/images/crops/spring/Potato.png",
    hasRecipe: true,
    quantity: 10,
    price: 25,
    stock: 22,
    name: "Croquetas de papa",
    ingredients: "500g de papas; Aceite; Sal; Pimienta",
    recipe:
      "Pelar y rallar las papas, colocarlas en un trapo y quitar el excedente de liquido. Calentar una sartén con aceite y agregar las papas en forma de disco, agregando la sal y la pimienta por encima. Cocinar vuelta y vuelta hasta conseguir una textura crocante y dorada por el exterior",
  },
  {
    bundle: "spring",
    id: 102,
    product: "Cafe",
    description: "remolacha",
    image: "src/resources/images/crops/spring/Coffee_Bean.png",
    hasRecipe: false,
    quantity: 10,
    price: 25,
    stock: 22,
    name: null,
    ingredients: null,
    recipe: null,
  },
  {
    bundle: "spring",
    id: 103,
    product: "Allium",
    description: "remolacha",
    image: "https://i.imgur.com/xTsjp3F.png",
    hasRecipe: false,
    quantity: 10,
    price: 25,
    stock: 22,
    name: null,
    ingredients: null,
    recipe: null,
  },
  {
    bundle: "spring",
    id: 104,
    product: "Tulipan",
    description: "remolacha",
    image: "src/resources/images/crops/spring/Tulip.png",
    hasRecipe: false,
    quantity: 10,
    price: 25,
    stock: 22,
    name: null,
    ingredients: null,
    recipe: null,
  },
  {
    bundle: "spring",
    id: 105,
    product: "Frambuesa",
    description: "remolacha",
    image: "src/resources/images/crops/spring/Blue_Jazz.png",
    hasRecipe: false,
    quantity: 10,
    price: 25,
    stock: 22,
    name: null,
    ingredients: null,
    recipe: null,
  },
  {
    bundle: "spring",
    id: 106,
    product: "Coliflor",
    description: "remolacha",
    image: "https://i.imgur.com/HKgKklR.png",
    hasRecipe: true,
    quantity: 10,
    price: 25,
    stock: 22,
    name: "Coliflor gratinada",
    ingredients:
      "1 coliflor; 125ml de leche; 2 huevos; queso rallado; pimienta; oregano; sal",
    recipe:
      "Partir la coliflor en pedazos y dejar cocer en una olla con poca agua salada. Precalentar el horno. En un bowl batir la leche y los huevos hasta tener una preparación homogénea, agregando la mitad del queso a la misma. Retirar la coliflor del fuego, escurrirla y colocarla en un molde para horno, bañándola con la mezcla liquida hecha previamente, agregando el resto del queso junto a los condimentos. Cocinar durante 20 minutos o hasta dorar",
  },
  {
    bundle: "spring",
    id: 107,
    product: "Col rizada",
    description: "remolacha",
    image: "src/resources/images/crops/spring/Kale.png",
    hasRecipe: true,
    quantity: 10,
    price: 25,
    stock: 22,
    name: "Sofrito",
    ingredients:
      "2 dientes de ajo; 1/4 de repollo; 1 paquete de col rizada; 2 cebollas; 1 zanahoria; 2 champiñones; aceite; 1 caldo a elección; sal; pimienta",
    recipe:
      "Colocar aceite en una sartén o wok, agregar los dientes de ajo y dorar revolviendo ocasionalmente para no quemarlo. Retirar del fuego y picar. Cortar las verduras duras en cubos y las horas en tiras, agregar las verduras al sartén usado previamente y remover hasta que estén blandos. Agregar el caldo, la sal y la pimienta a gusto, tapando y dejando cocinar el mismo al vapor por 5 minutos. Servir agregando el ajo picado por encima",
  },
  {
    bundle: "spring",
    id: 108,
    product: "Judia",
    description: "remolacha",
    image: "src/resources/images/crops/spring/Green_Bean.png",
    hasRecipe: false,
    quantity: 10,
    price: 25,
    stock: 22,
    name: null,
    ingredients: null,
    recipe: null,
  },
  {
    bundle: "spring",
    id: 109,
    product: "Fresa",
    description: "remolacha",
    image: "src/resources/images/crops/spring/Strawberry.png",
    hasRecipe: false,
    quantity: 10,
    price: 25,
    stock: 22,
    name: null,
    ingredients: null,
    recipe: null,
  },
  {
    bundle: "spring",
    id: 120,
    product: "Ruibarbo",
    description: "remolacha",
    image: "src/resources/images/crops/spring/Rhubarb.png",
    hasRecipe: true,
    quantity: 10,
    price: 25,
    stock: 22,
    name: "Tarta de ruibarbo",
    ingredients:
      "500g de ruibarbo; 175g de azúcar; 90g de harina común; 15g de manteca; masa de tarta",
    recipe:
      "Precalentar el horno a 230C. Colocar la masa en un molde, mezclar el azúcar y el harina, espolvoreando un cuarto de esta preparación sobre la masa. Agregar el ruibarbo cortado en cubos sobre la misma y agregar el resto de la mezcla. Agregar la manteca en trozos por toda la mezcla y tapar con el resto de la masa. Hornear por 15 minutos a fuego alto y luego cocinar por 40/45 minutos a 175C. Servir templado o frio",
  },
  {
    bundle: "spring",
    id: 111,
    product: "Puerro",
    description: "remolacha",
    image: "src/resources/images/crops/spring/Leek.png",
    hasRecipe: true,
    quantity: 10,
    price: 25,
    stock: 22,
    name: "Ensalada de puerro",
    ingredients:
      "3 puerros; 1 paquete de dientes de león; 1 aji morrón; 50g de nueces; aceite de oliva; sal; pimienta",
    recipe:
      "Cortar el puerro en rodajas finas, hervir durante 2 minutos y dejar reposar. Cortar el aji en cubos, cortar las hojas de diente de león y agregar ambos en un bowl junto a los puerros. Agregar el aceite, la sal y la pimienta, mezclando todo junto. Servir agregando las nueces picadas y las flores",
  },
  {
    bundle: "spring",
    id: 112,
    product: "Chirivia",
    description: "remolacha",
    image: "src/resources/images/crops/spring/Parsnip.png",
    hasRecipe: true,
    quantity: 10,
    price: 25,
    stock: 22,
    name: "Sopa de chirivía",
    ingredients:
      "150g de chirivía; 400g de zapallo; 1 cebolla; 500ml de agua; 500ml de leche, 15g de harina común; tomillo; vinagre; sal; pimienta",
    recipe:
      "Precalentar el horno a 200C, cortar la chirivía, el zapallo y la cebolla en cubos, agregar todo en un molde para horno con papel metálico en la base junto al tomillo con sal, aceite y pimienta. Cocinar por 30 minutos aproximadamente. Retirar y colocar en una olla con agua con fuego alto hasta que llegue a hervir, dejar cocinando por 10 minutos a fuego medio. Procesar los vegetales en la misma olla (o en una licuadora), agregando la mitad de la leche. Volver a ponerlo a fuego medio, agregando el resto de la leche mezclada con el harina y cocinar batiendo constantemente hasta conseguir la textura deseada, sin dejar que hierva",
  },
  {
    bundle: "spring",
    id: 113,
    product: "Ajo",
    description: "remolacha",
    image: "src/resources/images/crops/spring/Garlic.png",
    hasRecipe: false,
    quantity: 10,
    price: 25,
    stock: 22,
    name: null,
    ingredients: null,
    recipe: null,
  },
];

let packList = [
  {
    season: "primavera",
    id: "B1",
    className: "silver",
    detailUrl: "plata",
    description:
      "Papa: Un tubérculo cultivado en muchas zonas. Cafe: Plántalo en verano para tener un cafeto. Allium azul: Su flor crece con forma de esfera para invitar al máximo de mariposas posible. Tulipan: La más popular de las flores de primavera. Tiene un aroma dulce muy suave. Frambuesa: Una baya de primavera con el sabor del bosque.",
    price: 60,
    stock: 14,
    image1: "https://i.imgur.com/kDq8PJi.png",
    prodName1: "Papa",
    prodDesc1: "Un tubérculo cultivado en muchas zonas.",
    quantity1: 10,
    image2: "https://i.imgur.com/k2LWKUl.png",
    prodName2: "Cafe",
    prodDesc2: "Plántalo en verano para tener un cafeto.",
    quantity2: 10,
    image3: "https://i.imgur.com/xTsjp3F.png",
    prodName3: "Allium azul",
    prodDesc3:
      "Su flor crece con forma de esfera para invitar al máximo de mariposas posible.",
    quantity3: 10,
    image4: "https://i.imgur.com/2c3oyBa.png",
    prodName4: "Tulipan",
    prodDesc4:
      "La más popular de las flores de primavera, y tiene un aroma dulce muy suave.",
    quantity4: 10,
    image5: "https://i.imgur.com/tk1P6aa.png",
    prodName5: "Frambuesa",
    prodDesc5: "Una baya de primavera con el sabor del bosque.",
    quantity5: 10,
  },
  {
    season: "primavera",
    id: "B2",
    className: "gold",
    detailUrl: "oro",
    description:
      "Papa: Un tubérculo cultivado en muchas zonas. Cafe: Plántalo en verano para tener un cafeto. Allium azul: Su flor crece con forma de esfera para invitar al máximo de mariposas posible. Tulipan: La más popular de las flores de primavera. Tiene un aroma dulce muy suave. Frambuesa: Una baya de primavera con el sabor del bosque.",
    price: 95,
    stock: 21,
    image1: "https://i.imgur.com/HKgKklR.png",
    prodName1: "Coliflor",
    prodDesc1:
      "Valiosa, pero de crecimiento lento. A pesar de su palidez, sus cabezuelas están llenas de nutrientes.",
    quantity1: 10,
    image2: "https://i.imgur.com/ZvyGDjN.png",
    prodName2: "Col rizada",
    prodDesc2: "Sus hojas brillantes quedan genial en sopas y sofritos.",
    quantity2: 10,
    image3: "https://i.imgur.com/BUvGdbA.png",
    prodName3: "Judia verde",
    prodDesc3: "Una jugosa judía con un crujido fresco.",
    quantity3: 10,
    image4: "https://i.imgur.com/74hW90n.png",
    prodName4: "Fresa",
    prodDesc4:
      "Una fruta dulce, jugosa y de atractivo color rojo, muy apreciada.",
    quantity4: 10,
  },
  {
    season: "primavera",
    id: "B3",
    className: "iridium",
    detailUrl: "iridio",
    description:
      "Papa: Un tubérculo cultivado en muchas zonas. Cafe: Plántalo en verano para tener un cafeto. Allium azul: Su flor crece con forma de esfera para invitar al máximo de mariposas posible. Tulipan: La más popular de las flores de primavera. Tiene un aroma dulce muy suave. Frambuesa: Una baya de primavera con el sabor del bosque.",
    price: 120,
    stock: 11,
    image1: "https://i.imgur.com/sB2Xpzt.png",
    prodName1: "Ruibarbo",
    prodDesc1:
      "Sus tallos son tremendamente agrios, pero conforman un buen postre si se edulcoran.",
    quantity1: 10,
    image2: "https://i.imgur.com/8HxLxel.png",
    prodName2: "Puerro",
    prodDesc2: "Un delicioso pariente de la cebolla.",
    quantity2: 10,
    image3: "https://i.imgur.com/GCt2WZh.png",
    prodName3: "Chirivia",
    prodDesc3: "Un delicioso pariente de la cebolla.",
    quantity3: 10,
    image4: "https://i.imgur.com/TcBuPzc.png",
    prodName4: "Ajo",
    prodDesc4:
      "Añade un toque punzante y maravilloso a los platos. El ajo de alta calidad puede ser muy picante.",
    quantity4: 10,
  },
  {
    season: "verano",
    id: "B1",
    className: "silver",
    detailUrl: "plata",
    description:
      "Papa: Un tubérculo cultivado en muchas zonas. Cafe: Plántalo en verano para tener un cafeto. Allium azul: Su flor crece con forma de esfera para invitar al máximo de mariposas posible. Tulipan: La más popular de las flores de primavera. Tiene un aroma dulce muy suave. Frambuesa: Una baya de primavera con el sabor del bosque.",
    price: 60,
    stock: 13,
    image1: "https://i.imgur.com/9InoqAj.png",
    prodName1: "Arandano",
    prodDesc1:
      "Una baya muy popular que se dice tiene muchos beneficios para la salud. Su piel azulada es la que tiene la mayor concentración de nutrientes.",
    quantity1: 10,
    image2: "https://i.imgur.com/ZFPwMhA.png",
    prodName2: "Lupulo",
    prodDesc2:
      "Una flor amarga y ácida que se usa para dar sabor a la cerveza.",
    quantity2: 10,
    image3: "https://i.imgur.com/Rl2JLgq.png",
    prodName3: "Girasol",
    prodDesc3: "Hay un mito que dice que siempre gira buscando el sol.",
    quantity3: 10,
    image4: "https://i.imgur.com/YNNrc3P.png",
    prodName4: "Amapola",
    prodDesc4:
      "Además de su colorida flor, la amapola tiene usos culinarios y medicinales.",
    quantity4: 10,
    image5: "https://i.imgur.com/pSBkrXu.png",
    prodName5: "Helecho",
    prodDesc5: "Sus brotes tiernos son una especialidad comestible.",
    quantity5: 10,
  },
  {
    season: "verano",
    id: "B2",
    className: "gold",
    detailUrl: "oro",
    description:
      "Papa: Un tubérculo cultivado en muchas zonas. Cafe: Plántalo en verano para tener un cafeto. Allium azul: Su flor crece con forma de esfera para invitar al máximo de mariposas posible. Tulipan: La más popular de las flores de primavera. Tiene un aroma dulce muy suave. Frambuesa: Una baya de primavera con el sabor del bosque.",
    price: 95,
    stock: 26,
    image1: "https://i.imgur.com/4mcKop6.png",
    prodName1: "Maiz",
    prodDesc1:
      "Uno de los cereales más populares. Sus mazorcas frescas y dulces son un clásico del verano.",
    quantity1: 10,
    image2: "https://i.imgur.com/jxqBKlm.png",
    prodName2: "Lombarda",
    prodDesc2:
      "Se usa a menudo en ensaladas y chucrut. Su color puede variar entre lila, azul y amarillo verdoso según las condiciones del suelo.",
    quantity2: 10,
    image3: "https://i.imgur.com/vhMn4ry.png",
    prodName3: "Melon",
    prodDesc3: "Un capricho fresco y dulce de verano.",
    quantity3: 10,
    image4: "https://i.imgur.com/e4lcjs4.png",
    prodName4: "Lentejuela",
    prodDesc4:
      "Una flor tropical que prospera con el aire húmedo del verano. Tiene un aroma dulce y fuerte.",
    quantity4: 10,
  },
  {
    season: "verano",
    id: "B3",
    className: "iridium",
    detailUrl: "iridio",
    description:
      "Papa: Un tubérculo cultivado en muchas zonas. Cafe: Plántalo en verano para tener un cafeto. Allium azul: Su flor crece con forma de esfera para invitar al máximo de mariposas posible. Tulipan: La más popular de las flores de primavera. Tiene un aroma dulce muy suave. Frambuesa: Una baya de primavera con el sabor del bosque.",
    price: 120,
    stock: 4,
    image1: "https://i.imgur.com/lREVwys.png",
    prodName1: "Tomate",
    prodDesc1:
      "Rico y ligeramente agrio, el tomate tiene una gran variedad de usos en la cocina.",
    quantity1: 10,
    image2: "https://i.imgur.com/oFKLcDR.png",
    prodName2: "Rabano",
    prodDesc2:
      "Una raíz crujiente y refrescante con un toque de pimienta si se come crudo.",
    quantity2: 10,
    image3: "https://i.imgur.com/6gpNdHH.png",
    prodName3: "Chile",
    prodDesc3: "Pica como un demonio, pero tiene un toque de dulzura.",
    quantity3: 10,
    image4: "https://i.imgur.com/afgRwSb.png",
    prodName4: "Carambola",
    prodDesc4:
      "Una fruta muy jugosa que crece en climas cálidos y húmedos. Ligeramente dulce con un matiz ácido.",
    quantity4: 10,
  },
  {
    season: "otoño",
    id: "B1",
    className: "silver",
    detailUrl: "plata",
    description:
      "Papa: Un tubérculo cultivado en muchas zonas. Cafe: Plántalo en verano para tener un cafeto. Allium azul: Su flor crece con forma de esfera para invitar al máximo de mariposas posible. Tulipan: La más popular de las flores de primavera. Tiene un aroma dulce muy suave. Frambuesa: Una baya de primavera con el sabor del bosque.",
    price: 60,
    stock: 30,
    image1: "https://i.imgur.com/p5Et1RE.png",
    prodName1: "Ñame",
    prodDesc1:
      "Un tubérculo rico en almidón, con mucha versatilidad culinaria.",
    quantity1: 10,
    image2: "https://i.imgur.com/KFivjtP.png",
    prodName2: "Col china",
    prodDesc2: "Sus hojas verdes y sus tallos fibrosos son sanos y deliciosos.",
    quantity2: 10,
    image3: "https://i.imgur.com/q6JA44w.png",
    prodName3: "Baya dulce",
    prodDesc3: "Es, con diferencia, lo más dulce que has olido nunca.",
    quantity3: 10,
    image4: "https://i.imgur.com/KPOsupB.png",
    prodName4: "Rosa hada",
    prodDesc4:
      "Según una antigua leyenda popular, el olor de esta flor atrae a las hadas.",
    quantity4: 10,
    image5: "https://i.imgur.com/oSLCEbo.png",
    prodName5: "Mora",
    prodDesc5: "Un manjar de principios de otoño.",
    quantity5: 10,
  },
  {
    season: "otoño",
    id: "B2",
    className: "gold",
    detailUrl: "oro",
    description:
      "Papa: Un tubérculo cultivado en muchas zonas. Cafe: Plántalo en verano para tener un cafeto. Allium azul: Su flor crece con forma de esfera para invitar al máximo de mariposas posible. Tulipan: La más popular de las flores de primavera. Tiene un aroma dulce muy suave. Frambuesa: Una baya de primavera con el sabor del bosque.",
    price: 95,
    stock: 13,
    image1: "https://i.imgur.com/xmXyxxT.png",
    prodName1: "Alcachofa",
    prodDesc1:
      "El capullo de un cardo. Sus hojas espinosas esconden un interior carnoso y sustancioso.",
    quantity1: 10,
    image2: "https://i.imgur.com/UIY81fV.png",
    prodName2: "Grosella",
    prodDesc2: "Estas bayas ácidas y rojas se comen mucho en invierno.",
    quantity2: 10,
    image3: "https://i.imgur.com/a7R4cld.png",
    prodName3: "Remolacha",
    prodDesc3:
      "Una raíz dulce y sustanciosa. Además, sus hojas son excelentes para las ensaladas.",
    quantity3: 10,
    image4: "https://i.imgur.com/YxG5FzY.png",
    prodName4: "Maiz",
    prodDesc4:
      "Uno de los cereales más populares. Sus mazorcas frescas y dulces son un clásico del verano.",
    quantity4: 10,
  },
  {
    season: "otoño",
    id: "B3",
    className: "iridium",
    detailUrl: "iridio",
    description:
      "Papa: Un tubérculo cultivado en muchas zonas. Cafe: Plántalo en verano para tener un cafeto. Allium azul: Su flor crece con forma de esfera para invitar al máximo de mariposas posible. Tulipan: La más popular de las flores de primavera. Tiene un aroma dulce muy suave. Frambuesa: Una baya de primavera con el sabor del bosque.",
    price: 120,
    stock: 9,
    image1: "https://i.imgur.com/zUqbusq.png",
    prodName1: "Berenjena",
    prodDesc1:
      "Una verdura pariente del tomate, rica y saludable. Es deliciosa frita o en estofados.",
    quantity1: 10,
    image2: "https://i.imgur.com/KD2ARie.png",
    prodName2: "Calabaza",
    prodDesc2:
      "Una de las estrellas del otoño, cultivada por sus semillas crujientes y su carne de sabor delicado. Además, su cáscara hueca puede tallarse para hacer decoraciones festivas.",
    quantity2: 10,
    image3: "https://i.imgur.com/Sg4uh9S.png",
    prodName3: "Uva",
    prodDesc3: "Un dulce racimo de fruta.",
    quantity3: 10,
    image4: "https://i.imgur.com/ty8bZ7t.png",
    prodName4: "Amaranto",
    prodDesc4: "Un cereal lila cultivado por una antigua civilización.",
    quantity4: 10,
  },
  {
    season: "especiales",
    id: "B1",
    className: "silver",
    detailUrl: "plata",
    description:
      "Papa: Un tubérculo cultivado en muchas zonas. Cafe: Plántalo en verano para tener un cafeto. Allium azul: Su flor crece con forma de esfera para invitar al máximo de mariposas posible. Tulipan: La más popular de las flores de primavera. Tiene un aroma dulce muy suave. Frambuesa: Una baya de primavera con el sabor del bosque.",
    price: 60,
    stock: 19,
    image1: "https://i.imgur.com/375s7Vs.png",
    prodName1: "Miel",
    prodDesc1: "Néctar dulce producido por las abejas.",
    quantity1: 10,
    image2: "https://i.imgur.com/hfuHQiV.png",
    prodName2: "Cereza",
    prodDesc2: "Es popular y suele madurar antes que otras frutas.",
    quantity2: 10,
    image3: "https://i.imgur.com/OkPGOVS.png",
    prodName3: "Naranja",
    prodDesc3: "Jugosa, intensa y rebosante de dulce aroma veraniego.",
    quantity3: 10,
    image4: "https://i.imgur.com/DU4SjMU.png",
    prodName4: "Melocoton",
    prodDesc4: "Un poco peludito al tacto.",
    quantity4: 10,
    image5: "https://i.imgur.com/jNkPBL7.png",
    prodName5: "Coco",
    prodDesc5: "El fruto del cocotero. Tiene muchos usos en la cocina.",
    quantity5: 10,
  },
  {
    season: "especiales",
    id: "B2",
    className: "gold",
    detailUrl: "oro",
    description: `${"Papa: Un tubérculo cultivado en muchas zonas. Cafe: Plántalo en verano para tener un cafeto. Allium azul: Su flor crece con forma de esfera para invitar al máximo de mariposas posible. Tulipan: La más popular de las flores de primavera. Tiene un aroma dulce muy suave. Frambuesa: Una baya de primavera con el sabor del bosque."}`,
    stock: 20,
    image1: "https://i.imgur.com/rxssQeQ.png",
    price: "70",
    prodName1: "Albaricoque",
    prodDesc1: "Una fruta tierna y pequeña con un hueso duro como una piedra.",
    quantity1: 10,
    image2: "https://i.imgur.com/PlER97J.png",
    prodName2: "Platano",
    prodDesc2: "Una dulce, almidonada fruta tropical.",
    quantity2: 10,
    image3: "https://i.imgur.com/Y7JJlj5.png",
    prodName3: "Mayonesa",
    prodDesc3: "Da ganas de untarla.",
    quantity3: 10,
    image4: "https://i.imgur.com/6V46Bp1.png",
    prodName4: "Pale Ale",
    prodDesc4: "Bebe con moderación.",
    quantity4: 10,
  },
  {
    season: "especiales",
    id: "B3",
    className: "iridium",
    detailUrl: "iridio",
    description:
      "Papa: Un tubérculo cultivado en muchas zonas. Cafe: Plántalo en verano para tener un cafeto. Allium azul: Su flor crece con forma de esfera para invitar al máximo de mariposas posible. Tulipan: La más popular de las flores de primavera. Tiene un aroma dulce muy suave. Frambuesa: Una baya de primavera con el sabor del bosque.",
    price: 120,
    stock: 20,
    image1: "https://i.imgur.com/g9IuOCo.png",
    prodName1: "Mango",
    prodDesc1: "Una gran, dulce fruta tropical con un sabor único.",
    quantity1: 10,
    image2: "https://i.imgur.com/UFamyib.png",
    prodName2: "Manzana",
    prodDesc2: "Una fruta crujiente que se usa para hacer zumo y sidra.",
    quantity2: 10,
    image3: "https://i.imgur.com/2Ypt1jn.png",
    prodName3: "Queso",
    prodDesc3: "Queso normal y corriente.",
    quantity3: 10,
    image4: "https://i.imgur.com/c9XTkbb.png",
    prodName4: "Granada",
    prodDesc4: "Dentro de esta fruta hay racimos de jugosas semillas.",
    quantity4: 10,
  },
];

//

const getFetchForFilter = new Promise((res) => {
  setTimeout(() => {
    res(packList);
  }, 2000);
});

const ItemDetailContainer = ({ classForNight }) => {
  const [filteredList, setFilteredList] = useState([]);
  const { seasonUrl } = useParams();

  useEffect(() => {
    getFetchForFilter
      .then((res) =>
        res.filter((filteredRes) => filteredRes.season == seasonUrl)
      )
      .then((res) => setFilteredList(res))
      .catch((err) => console.log(err));
  }, []);

  return (
    <div className="d-flex flex-wrap w-100 justify-content-around gap-4 p-4 containerDetails">
      <ItemDetail pack={filteredList} isNight={classForNight} />
    </div>
  );
};

export default ItemDetailContainer;
